import base64
import os
import re
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader

def generate_pdf_report(user: dict, scan: dict, pdf_path: str):
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "DermaXplain - Skin Scan Report")

    # User Details
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 100, f"Name: {user.get('name')}")
    c.drawString(50, height - 120, f"Email: {user.get('email')}")

    # Patient & Scan Details
    c.drawString(50, height - 160, f"Patient Name: {scan.get('patient_name')}")
    c.drawString(50, height - 180, f"Age: {scan.get('patient_age')}")
    c.drawString(50, height - 200, f"Gender: {scan.get('gender')}")
    c.drawString(50, height - 220, f"Scan Area: {scan.get('scan_area')}")
    c.drawString(50, height - 240, f"Additional Info: {scan.get('additional_info', 'N/A')}")
    c.drawString(50, height - 260, f"Prediction: {scan['prediction']['class']}")
    c.drawString(50, height - 280, f"Confidence: {scan['prediction']['confidence']*100:.2f}%")

    # Save base64 image to a temporary file
    image_path = f"temp_uploads/{scan.get('image_filename', 'scan_image.jpg')}"
    try:
        image_base64 = scan["image_base64"]

        # Remove prefix if present
        if image_base64.startswith("data:image"):
            image_base64 = re.sub(r"^data:image\/[a-zA-Z]+;base64,", "", image_base64)

        # Fix padding if needed
        missing_padding = len(image_base64) % 4
        if missing_padding:
            image_base64 += "=" * (4 - missing_padding)

        # Decode and write image
        with open(image_path, "wb") as f:
            f.write(base64.b64decode(image_base64))

        # Draw image
        c.drawImage(ImageReader(image_path), 50, height - 550, width=300, height=250, preserveAspectRatio=True)
    except Exception as e:
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(50, height - 560, f"[Error loading image: {e}]")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "This report was auto-generated by DermaXplain.")

    c.save()

    # Cleanup image
    if os.path.exists(image_path):
        os.remove(image_path)
